### ISSUE TITLE
typo - docs icon

### ISSUE THREAD

**Issue by JustinWebDev** [gl-inet/docs4.x#3]
https://docs.gl-inet.com/router/en/4/interface_guide/clients/#limiting-speed
says "three docs icon"
Should this be "three dots icon"?

NOTE:  You use "Action" elsewhere, which the pics show the UI as having that, so it would be good to use it universally.  At least be consistent.

**Comment by linmq** [comment]
Thank you very much for your suggestions!  I had fixed and deployed it.
